apiVersion: apps/v1
kind: Deployment
metadata:
  name: xnginx-deployment
  labels:
    app: xnginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xnginx
  template:
    metadata:
      labels:
        app: xnginx
    spec:
      containers:
      - name: xnginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
