apiVersion: apps/v1
kind: Deployment
metadata:
  name: saturday-deployment
  labels:
    app: saturday-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: saturday-nginx
  template:
    metadata:
      labels:
        app: saturday-nginx
    spec:
      containers:
      - name: saturday-nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: saturday-nginx-service
spec:
  selector:
    app: saturday-nginx
  ports:
    - protocol: TCP
      port: 80
