apiVersion: apps/v1
kind: Deployment
metadata:
  name: xnginx-deployment
  labels:
    app: xnginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xnginx
  template:
    metadata:
      labels:
        app: xnginx
    spec:
      containers:
      - name: xnginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysite-xnginx-service
spec:
  selector:
    app: xnginx
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mysite-nginx-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Path(`/mccoy`)
    kind: Rule
    services:
    - name: mysite-xnginx-service
      port: 80
    middlewares:
      - name: dashboard-stripprefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dashboard-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /mccoy
