apiVersion: apps/v1
kind: Deployment
metadata:
  name: zzzzvolume-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume-test
  template:
    metadata:
      labels:
        app: volume-test
    spec:
      containers:
      - name: volume-test
        image: httpd:latest
        volumeMounts:
        - name: volv
          mountPath: /usr/local/apache2/htdocs
        ports:
          - containerPort: 80
      volumes:
      - name: volv
        persistentVolumeClaim:
            claimName: local-path-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: myvolumn-nginx-service
spec:
  type: NodePort
  selector:
    app: volume-test
  ports:
    - protocol: TCP
      port: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: myvolumn-nginx-service
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /mccoy
            pathType: Prefix
            backend:
              service:
                name: myvolumn-nginx-service
                port:
                  number: 80
