apiVersion: apps/v1
kind: Deployment
metadata:
  name: xnginx-deployment
  labels:
    app: xnginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xnginx
  template:
    metadata:
      labels:
        app: xnginx
    spec:
      containers:
      - name: xnginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysite-xnginx-service
spec:
  type: NodePort
  selector:
    app: xnginx
  ports:
    - protocol: TCP
      port: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: fooxnginx-service
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /mccoy
            pathType: Prefix
            backend:
              service:
                name: mysite-xnginx-service 
                port:
                  number: 80
