apiVersion: apps/v1
kind: Deployment
metadata:
  name: xnginx-deployment
  labels:
    app: xnginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xnginx
  template:
    metadata:
      labels:
        app: xnginx
    spec:
      containers:
      - name: xnginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysite-xnginx-service
spec:
  selector:
    app: xnginx
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: michael.globaldrum.com
    http:
      paths:
      - pathType: Prefix
        path: /nxginx
        backend:
          service:
            name: mysite-xnginx-service 
            port:
              number: 80
