apiVersion: apps/v1
kind: Deployment
metadata:
  name: saturday-deployment
  labels:
    app: saturday-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: saturday-nginx
  template:
    metadata:
      labels:
        app: saturday-nginx
    spec:
      containers:
      - name: saturday-nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: saturday-nginx-service
spec:
  selector:
    app: saturday-nginx
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: michael-globaldrum-com
  namespace: testargo 
spec:
  secretName: michael-globaldrum-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - michael.globaldrum.com
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mysite-nginx-ingress
  namespace: testargo
spec:
  entryPoints:
    - websecure
  routes:
  - match: Path(`/saturday`)
    kind: Rule
    services:
    - name: saturday-nginx-service
      port: 80
    middlewares:
      - name: dashboard-stripprefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dashboard-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /saturday
